 Preparing Mexico Data

Import
The first part of any data science project is preparing your data, which means making sure its in the right place and format for you to conduct your analysis. The first step of any data preparation is importing your raw data and cleaning it.

Task 1.2.1: Read these three files into three separate DataFrames named df1, df2, and df3, respectively.

In [6]:
import pandas  as pd

df1 = pd.read_csv("mexico_real_estate.csv")
df2 = pd.read_csv("mexico_real_estate_2.csv")
df3 = pd.read_csv("mexico_real_estate_3.csv")

Clean df1
Task 1.2.2: Inspect df1 by looking at its shape attribute. Then use the info method to see the data types and number of missing values for each column. Finally, use the head method to determine to look at the first five rows of your dataset.

In [2]:
print(df1.shape)
print(df1.head(10))
print(df1.dtypes)
print(df1.isnull().sum())

(700, 6)
  property_type              state        lat         lon  area_m2  \
0         condo          Chihuahua  28.974293 -106.101605    269.7
1           NaN          chihuahua  28.855726 -106.089580    268.2
2     apartment   CIUDAD DE MEXICO  19.163374  -98.950584    108.6
3     Townhouse             Sonora  29.133288 -110.791352   -282.8
4       Terreno       QUINTANA ROO  19.717641  -88.401013     81.1
5           NaN            Puebla   19.832804  -98.157409     76.2
6           NaN            Chiapas  17.433676  -93.821787     75.1
7   Apartamento         nuevo leon  25.535722  -99.979541    310.0
8          Land  Ciudad de Mexico   20.067603  -99.145325    204.8
9           NaN          Veracruz   18.612036  -96.627109    145.9

     price_usd
0          NaN
1    327355.13
2   7215680.28
3  18965969.11
4  11297383.16
5    120334.21
6    113975.81
7    468041.13
8  $121,627.07
9    125412.34
property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd            str
dtype: object
property_type    75
state             0
lat              21
lon              17
area_m2          18
price_usd        18
dtype: int64

In [5]:
import pandas as pd


df1 = pd.read_csv("mexico_real_estate.csv")
df1.head(10)

,property_type,state,lat,lon,area_m2,price_usd
0,condo,Chihuahua,28.974293,-106.101605,269.7,NaN
1,NaN,chihuahua,28.855726,-106.089580,268.2,327355.13
2,apartment,CIUDAD DE MEXICO,19.163374,-98.950584,108.6,7215680.28
3,Townhouse,Sonora,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,QUINTANA ROO,19.717641,-88.401013,81.1,11297383.16
5,NaN,Puebla,19.832804,-98.157409,76.2,120334.21
6,NaN,Chiapas,17.433676,-93.821787,75.1,113975.81
7,Apartamento,nuevo leon,25.535722,-99.979541,310.0,468041.13
8,Land,Ciudad de Mexico,20.067603,-99.145325,204.8,"$121,627.07"
9,NaN,Veracruz,18.612036,-96.627109,145.9,125412.34

It looks like there are a couple of problems in this DataFrame that you need to solve. First, there are many rows with NaN values in the "lat" and "lon" columns. Second, the data type for the "price_usd" column is object when it should be float.

Task 1.2.3: Clean df1 by dropping rows with NaN values. Then remove the "$" and "," characters from "price_usd" and recast the values in the column as floats

In [7]:
#To drop rows with missing values from a DataFrame in pandas, use the dropna() method.
# By default, df.dropna() removes any row that contains at least one missing value (NaN or None) and returns a new DataFrame.
df1 = df1.dropna()

df1

,property_type,state,lat,lon,area_m2,price_usd
2,apartment,CIUDAD DE MEXICO,19.163374,-98.950584,108.6,7215680.28
3,Townhouse,Sonora,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,QUINTANA ROO,19.717641,-88.401013,81.1,11297383.16
7,Apartamento,nuevo leon,25.535722,-99.979541,310.0,468041.13
8,Land,Ciudad de Mexico,20.067603,-99.145325,204.8,"$121,627.07"
...,...,...,...,...,...,...
694,Casa,Veracruz,19.499826,-96.809236,262.3,"$304,019.47"
695,Apartamento,guanajuato,21.451530,-101.002477,365.6,640845.89
696,House,Sonora,28.593113,-110.534134,54.8,26694.43
697,Land,Veracruz,19.407603,-96.871573,252.5,213576.35
699,Villa,Puebla,18.806063,-97.441883,323.4,244524.77

In [8]:
#To replace string characters in a pandas column, use the .str.replace() method.
# This allows you to target a specific column and swap characters or text patterns.

df1['price_usd'] = df1['price_usd'].str.replace('$', '').str.replace(',', '').astype(float)

df1

,property_type,state,lat,lon,area_m2,price_usd
2,apartment,CIUDAD DE MEXICO,19.163374,-98.950584,108.6,7215680.28
3,Townhouse,Sonora,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,QUINTANA ROO,19.717641,-88.401013,81.1,11297383.16
7,Apartamento,nuevo leon,25.535722,-99.979541,310.0,468041.13
8,Land,Ciudad de Mexico,20.067603,-99.145325,204.8,121627.07
...,...,...,...,...,...,...
694,Casa,Veracruz,19.499826,-96.809236,262.3,304019.47
695,Apartamento,guanajuato,21.451530,-101.002477,365.6,640845.89
696,House,Sonora,28.593113,-110.534134,54.8,26694.43
697,Land,Veracruz,19.407603,-96.871573,252.5,213576.35
699,Villa,Puebla,18.806063,-97.441883,323.4,244524.77

Clean df2
Now it's time to tackle df2. This frame has the same missing-value issue as the other datasets, but here the values are already in US dollars, so the main task is to remove incomplete rows and keep the numeric price data consistent.

After cleaning, the DataFrame contains columns such as property_type, state, lat, lon, area_m2, and price_usd. Rows with missing values in key fields are dropped so the frame is ready for comparison and analysis.

Task 1.2.4: Drop rows with NaN values in df2. Then confirm that the remaining data is in a usable numeric form, with the price column stored as a float and the cleaned frame ready for comparison.

In [ ]:
df2.head(10)

  property_type             state        lat         lon  area_m2    price_usd
0         Condo         Michoacan  28.974293 -106.101605    269.7          NaN
1         House  Ciudad de Mexico  28.855726 -106.089580    268.2    327355.13
2         villa            OAXACA  19.163374  -98.950584    108.6   7215680.28
3  Departamento           Yucatan  29.133288 -110.791352   -282.8  18965969.11
4       Terreno          Veracruz  19.717641  -88.401013     81.1  11297383.16
5         Condo            puebla  19.832804  -98.157409     76.2    120334.21
6         HOUSE   Baja California  17.433676  -93.821787     75.1    113975.81
7     Apartment      Quintana Roo  25.535722  -99.979541    310.0    468041.13
8         house        Guanajuato  20.067603  -99.145325    204.8  $121,627.07
9     townhouse       Guanajuato   18.612036  -96.627109    145.9    125412.34

In [10]:
df2['price_usd'] = df2['price_usd'].str.replace('$', '').str.replace(',', '').astype(float)

df2

,property_type,state,lat,lon,area_m2,price_usd
0,Condo,Michoacan,28.974293,-106.101605,269.7,NaN
1,House,Ciudad de Mexico,28.855726,-106.089580,268.2,327355.13
2,villa,OAXACA,19.163374,-98.950584,108.6,7215680.28
3,Departamento,Yucatan,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,Veracruz,19.717641,-88.401013,81.1,11297383.16
...,...,...,...,...,...,...
695,land,puebla,21.451530,-101.002477,365.6,640845.89
696,House,Baja California,28.593113,-110.534134,54.8,26694.43
697,villa,Chiapas,19.407603,-96.871573,252.5,213576.35
698,House,Coahuila,NaN,-99.068259,347.7,316275.25
699,townhouse,Coahuila,18.806063,-97.441883,323.4,244524.77

In [11]:
df2 = df2.dropna()
df2

,property_type,state,lat,lon,area_m2,price_usd
1,House,Ciudad de Mexico,28.855726,-106.089580,268.2,327355.13
2,villa,OAXACA,19.163374,-98.950584,108.6,7215680.28
3,Departamento,Yucatan,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,Veracruz,19.717641,-88.401013,81.1,11297383.16
5,Condo,puebla,19.832804,-98.157409,76.2,120334.21
...,...,...,...,...,...,...
692,Villa,CDMX,19.329731,-87.989164,46.7,80386.49
695,land,puebla,21.451530,-101.002477,365.6,640845.89
696,House,Baja California,28.593113,-110.534134,54.8,26694.43
697,villa,Chiapas,19.407603,-96.871573,252.5,213576.35
699,townhouse,Coahuila,18.806063,-97.441883,323.4,244524.77