 Preparing Mexico Data

Import
The first part of any data science project is preparing your data, which means making sure its in the right place and format for you to conduct your analysis. The first step of any data preparation is importing your raw data and cleaning it.

Task 1.2.1: Read these three files into three separate DataFrames named df1, df2, and df3, respectively.

In [6]:
import pandas  as pd

df1 = pd.read_csv("mexico_real_estate.csv")
df2 = pd.read_csv("mexico_real_estate_2.csv")
df3 = pd.read_csv("mexico_real_estate_3.csv")

Clean df1
Task 1.2.2: Inspect df1 by looking at its shape attribute. Then use the info method to see the data types and number of missing values for each column. Finally, use the head method to determine to look at the first five rows of your dataset.

In [2]:
print(df1.shape)
print(df1.head(10))
print(df1.dtypes)
print(df1.isnull().sum())

(700, 6)
  property_type              state        lat         lon  area_m2  \
0         condo          Chihuahua  28.974293 -106.101605    269.7
1           NaN          chihuahua  28.855726 -106.089580    268.2
2     apartment   CIUDAD DE MEXICO  19.163374  -98.950584    108.6
3     Townhouse             Sonora  29.133288 -110.791352   -282.8
4       Terreno       QUINTANA ROO  19.717641  -88.401013     81.1
5           NaN            Puebla   19.832804  -98.157409     76.2
6           NaN            Chiapas  17.433676  -93.821787     75.1
7   Apartamento         nuevo leon  25.535722  -99.979541    310.0
8          Land  Ciudad de Mexico   20.067603  -99.145325    204.8
9           NaN          Veracruz   18.612036  -96.627109    145.9

     price_usd
0          NaN
1    327355.13
2   7215680.28
3  18965969.11
4  11297383.16
5    120334.21
6    113975.81
7    468041.13
8  $121,627.07
9    125412.34
property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd            str
dtype: object
property_type    75
state             0
lat              21
lon              17
area_m2          18
price_usd        18
dtype: int64

In [5]:
import pandas as pd


df1 = pd.read_csv("mexico_real_estate.csv")
df1.head(10)

,property_type,state,lat,lon,area_m2,price_usd
0,condo,Chihuahua,28.974293,-106.101605,269.7,NaN
1,NaN,chihuahua,28.855726,-106.089580,268.2,327355.13
2,apartment,CIUDAD DE MEXICO,19.163374,-98.950584,108.6,7215680.28
3,Townhouse,Sonora,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,QUINTANA ROO,19.717641,-88.401013,81.1,11297383.16
5,NaN,Puebla,19.832804,-98.157409,76.2,120334.21
6,NaN,Chiapas,17.433676,-93.821787,75.1,113975.81
7,Apartamento,nuevo leon,25.535722,-99.979541,310.0,468041.13
8,Land,Ciudad de Mexico,20.067603,-99.145325,204.8,"$121,627.07"
9,NaN,Veracruz,18.612036,-96.627109,145.9,125412.34

It looks like there are a couple of problems in this DataFrame that you need to solve. First, there are many rows with NaN values in the "lat" and "lon" columns. Second, the data type for the "price_usd" column is object when it should be float.

Task 1.2.3: Clean df1 by dropping rows with NaN values. Then remove the "$" and "," characters from "price_usd" and recast the values in the column as floats

In [7]:
#To drop rows with missing values from a DataFrame in pandas, use the dropna() method.
# By default, df.dropna() removes any row that contains at least one missing value (NaN or None) and returns a new DataFrame.
df1 = df1.dropna()

df1

,property_type,state,lat,lon,area_m2,price_usd
2,apartment,CIUDAD DE MEXICO,19.163374,-98.950584,108.6,7215680.28
3,Townhouse,Sonora,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,QUINTANA ROO,19.717641,-88.401013,81.1,11297383.16
7,Apartamento,nuevo leon,25.535722,-99.979541,310.0,468041.13
8,Land,Ciudad de Mexico,20.067603,-99.145325,204.8,"$121,627.07"
...,...,...,...,...,...,...
694,Casa,Veracruz,19.499826,-96.809236,262.3,"$304,019.47"
695,Apartamento,guanajuato,21.451530,-101.002477,365.6,640845.89
696,House,Sonora,28.593113,-110.534134,54.8,26694.43
697,Land,Veracruz,19.407603,-96.871573,252.5,213576.35
699,Villa,Puebla,18.806063,-97.441883,323.4,244524.77

In [8]:
#To replace string characters in a pandas column, use the .str.replace() method.
# This allows you to target a specific column and swap characters or text patterns.

df1['price_usd'] = df1['price_usd'].str.replace('$', '').str.replace(',', '').astype(float)

df1

,property_type,state,lat,lon,area_m2,price_usd
2,apartment,CIUDAD DE MEXICO,19.163374,-98.950584,108.6,7215680.28
3,Townhouse,Sonora,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,QUINTANA ROO,19.717641,-88.401013,81.1,11297383.16
7,Apartamento,nuevo leon,25.535722,-99.979541,310.0,468041.13
8,Land,Ciudad de Mexico,20.067603,-99.145325,204.8,121627.07
...,...,...,...,...,...,...
694,Casa,Veracruz,19.499826,-96.809236,262.3,304019.47
695,Apartamento,guanajuato,21.451530,-101.002477,365.6,640845.89
696,House,Sonora,28.593113,-110.534134,54.8,26694.43
697,Land,Veracruz,19.407603,-96.871573,252.5,213576.35
699,Villa,Puebla,18.806063,-97.441883,323.4,244524.77

Clean df2
Now it's time to tackle df2. This frame has the same missing-value issue as the other datasets, but here the values are already in US dollars, so the main task is to remove incomplete rows and keep the numeric price data consistent.

After cleaning, the DataFrame contains columns such as property_type, state, lat, lon, area_m2, and price_usd. Rows with missing values in key fields are dropped so the frame is ready for comparison and analysis.

Task 1.2.4: Drop rows with NaN values in df2. Then confirm that the remaining data is in a usable numeric form, with the price column stored as a float and the cleaned frame ready for comparison.

In [ ]:
df2.head(10)

  property_type             state        lat         lon  area_m2    price_usd
0         Condo         Michoacan  28.974293 -106.101605    269.7          NaN
1         House  Ciudad de Mexico  28.855726 -106.089580    268.2    327355.13
2         villa            OAXACA  19.163374  -98.950584    108.6   7215680.28
3  Departamento           Yucatan  29.133288 -110.791352   -282.8  18965969.11
4       Terreno          Veracruz  19.717641  -88.401013     81.1  11297383.16
5         Condo            puebla  19.832804  -98.157409     76.2    120334.21
6         HOUSE   Baja California  17.433676  -93.821787     75.1    113975.81
7     Apartment      Quintana Roo  25.535722  -99.979541    310.0    468041.13
8         house        Guanajuato  20.067603  -99.145325    204.8  $121,627.07
9     townhouse       Guanajuato   18.612036  -96.627109    145.9    125412.34

In [10]:
df2['price_usd'] = df2['price_usd'].str.replace('$', '').str.replace(',', '').astype(float)

df2

,property_type,state,lat,lon,area_m2,price_usd
0,Condo,Michoacan,28.974293,-106.101605,269.7,NaN
1,House,Ciudad de Mexico,28.855726,-106.089580,268.2,327355.13
2,villa,OAXACA,19.163374,-98.950584,108.6,7215680.28
3,Departamento,Yucatan,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,Veracruz,19.717641,-88.401013,81.1,11297383.16
...,...,...,...,...,...,...
695,land,puebla,21.451530,-101.002477,365.6,640845.89
696,House,Baja California,28.593113,-110.534134,54.8,26694.43
697,villa,Chiapas,19.407603,-96.871573,252.5,213576.35
698,House,Coahuila,NaN,-99.068259,347.7,316275.25
699,townhouse,Coahuila,18.806063,-97.441883,323.4,244524.77

In [11]:
df2 = df2.dropna()
df2

,property_type,state,lat,lon,area_m2,price_usd
1,House,Ciudad de Mexico,28.855726,-106.089580,268.2,327355.13
2,villa,OAXACA,19.163374,-98.950584,108.6,7215680.28
3,Departamento,Yucatan,29.133288,-110.791352,-282.8,18965969.11
4,Terreno,Veracruz,19.717641,-88.401013,81.1,11297383.16
5,Condo,puebla,19.832804,-98.157409,76.2,120334.21
...,...,...,...,...,...,...
692,Villa,CDMX,19.329731,-87.989164,46.7,80386.49
695,land,puebla,21.451530,-101.002477,365.6,640845.89
696,House,Baja California,28.593113,-110.534134,54.8,26694.43
697,villa,Chiapas,19.407603,-96.871573,252.5,213576.35
699,townhouse,Coahuila,18.806063,-97.441883,323.4,244524.77

Clean df3
 We're now on the final DataFrame. Use the same shape, info and head commands to inspect the df3. Do you see any familiar issues?

You'll notice that we still have NaN values, but there are two new problems:

Instead of separate "lat" and "lon" columns, there's a single "lat-lon" column.
Instead of a "state" column, there's a "place_with_parent_names" column.
We need the resolve these problems so that df3 has the same columns in the same format as df1 and df2

In [14]:
print(df3.shape)
print(df3.head(10))
print(df3.dtypes)
print(df3.isnull().sum())

df3

(700, 5)
  property_type               place_with_parent_names  \
0     Apartment             Mexico|Nuevo Leon|Apodaca
1         condo            Mexico|Jalisco|Guadalajara
2   Apartamento       Mexico|Baja California|Ensenada
3         villa           Mexico|Quintana Roo|Cozumel
4          land                 Mexico|Puebla|Atlixco
5         HOUSE      Mexico|Puebla|Puebla de Zaragoza
6     apartment  Mexico|Quintana Roo|Playa del Carmen
7         Condo                Mexico|Oaxaca|Huatulco
8         HOUSE              Mexico|Coahuila|Monclova
9         condo                Mexico|Guanajuato|Leon

                                  lat-lon  area_m2    price_usd
0   26.272386538797807,-99.69333858664358    374.1    198546.39
1  21.179816414272228,-103.90928381708474    350.1    192501.01
2   30.75686615263983,-114.61153555826392    314.5          NaN
3    18.402178035272414,-88.6815511701174    292.1    338234.86
4    19.704376168280493,-98.6765463059634    291.3    143420.13
5   18.975900448784394,-97.90542890349666    365.4    129193.79
6    18.93073034081085,-87.88455182271785    376.7    671737.63
7   17.649145240898292,-96.86048246601753     49.0     23459.96
8     27.44369666449057,-101.197436163446    149.7    142291.93
9  21.191533406392164,-101.08404505385387     82.9  19833634.66
property_type                  str
place_with_parent_names        str
lat-lon                        str
area_m2                    float64
price_usd                      str
dtype: object
property_type              89
place_with_parent_names    17
lat-lon                    25
area_m2                    27
price_usd                  28
dtype: int64

,property_type,place_with_parent_names,lat-lon,area_m2,price_usd
0,Apartment,Mexico|Nuevo Leon|Apodaca,"26.272386538797807,-99.69333858664358",374.1,198546.39
1,condo,Mexico|Jalisco|Guadalajara,"21.179816414272228,-103.90928381708474",350.1,192501.01
2,Apartamento,Mexico|Baja California|Ensenada,"30.75686615263983,-114.61153555826392",314.5,NaN
3,villa,Mexico|Quintana Roo|Cozumel,"18.402178035272414,-88.6815511701174",292.1,338234.86
4,land,Mexico|Puebla|Atlixco,"19.704376168280493,-98.6765463059634",291.3,143420.13
...,...,...,...,...,...
695,Apartamento,Mexico|Veracruz|Coatzacoalcos,"18.875043194383732,-96.6902796375128",402.7,"$174,512.33"
696,HOUSE,Mexico|Distrito Federal|Iztapalapa,"19.605826607779502,-98.59748258584555",183.9,158687.22
697,house,Mexico|Baja California|Rosarito,"30.17419350415885,-114.86955472156812",NaN,453488.36
698,Terreno,Mexico|Chihuahua|Delicias,"27.897171379287602,-106.84506261706102",NaN,117215.63
699,House,Mexico|Nuevo Leon,"24.841765981145397,-99.93170869556052",-409.1,311956.49

Task 1.2.5: Drop rows with NaN values in df3. Then use the split method to create two new columns from "lat-lon" named "lat" and "lon", respectively.

In [15]:
#To split strings in one column and create new columns from the result in pandas, use the .str.split() method with expand=True.
#df["col"].str.split(sep) splits each string by sep (default is whitespace).
#expand=True turns the list of split parts into separate columns (returns a DataFrame).
#Assigning to df[["new1", "new2", ...]] creates those new columns in one step.
#n=1 means “split at most once”, so you get exactly two columns even if there are more commas
df3[["lat","lon"]] = df3["lat-lon"].str.split(",",n = 1, expand=True)

df3 = df3.drop(columns=["lat-lon"])

df3

,property_type,place_with_parent_names,area_m2,price_usd,lat,lon
0,Apartment,Mexico|Nuevo Leon|Apodaca,374.1,198546.39,26.272386538797807,-99.69333858664358
1,condo,Mexico|Jalisco|Guadalajara,350.1,192501.01,21.179816414272228,-103.90928381708474
2,Apartamento,Mexico|Baja California|Ensenada,314.5,NaN,30.75686615263983,-114.61153555826392
3,villa,Mexico|Quintana Roo|Cozumel,292.1,338234.86,18.402178035272414,-88.6815511701174
4,land,Mexico|Puebla|Atlixco,291.3,143420.13,19.704376168280493,-98.6765463059634
...,...,...,...,...,...,...
695,Apartamento,Mexico|Veracruz|Coatzacoalcos,402.7,"$174,512.33",18.875043194383732,-96.6902796375128
696,HOUSE,Mexico|Distrito Federal|Iztapalapa,183.9,158687.22,19.605826607779502,-98.59748258584555
697,house,Mexico|Baja California|Rosarito,NaN,453488.36,30.17419350415885,-114.86955472156812
698,Terreno,Mexico|Chihuahua|Delicias,NaN,117215.63,27.897171379287602,-106.84506261706102
699,House,Mexico|Nuevo Leon,-409.1,311956.49,24.841765981145397,-99.93170869556052

In [16]:
df3 = df3.dropna()
df3['price_usd'] = df3['price_usd'].str.replace('$', '').str.replace(',', '').astype(float)

df3

,property_type,place_with_parent_names,area_m2,price_usd,lat,lon
0,Apartment,Mexico|Nuevo Leon|Apodaca,374.1,198546.39,26.272386538797807,-99.69333858664358
1,condo,Mexico|Jalisco|Guadalajara,350.1,192501.01,21.179816414272228,-103.90928381708474
3,villa,Mexico|Quintana Roo|Cozumel,292.1,338234.86,18.402178035272414,-88.6815511701174
4,land,Mexico|Puebla|Atlixco,291.3,143420.13,19.704376168280493,-98.6765463059634
5,HOUSE,Mexico|Puebla|Puebla de Zaragoza,365.4,129193.79,18.975900448784394,-97.90542890349666
...,...,...,...,...,...,...
693,condo,Mexico|Puebla|Cholula,388.8,634100.21,19.17785272566725,-97.99839861164253
694,house,Mexico|Nuevo Leon|Monterrey,305.1,204682.44,25.35786413008344,-100.56425311370224
695,Apartamento,Mexico|Veracruz|Coatzacoalcos,402.7,174512.33,18.875043194383732,-96.6902796375128
696,HOUSE,Mexico|Distrito Federal|Iztapalapa,183.9,158687.22,19.605826607779502,-98.59748258584555
699,House,Mexico|Nuevo Leon,-409.1,311956.49,24.841765981145397,-99.93170869556052

Task 1.2.6: Use the split method again, this time to extract the state for every house. (Note that the state name always appears after "México|" in each string.) Use this information to create a "state" column. Finally, drop the "place_with_parent_names" and "lat-lon" columns from the DataFrame

In [17]:
#Creating just one new column from a split
#If you only need one part of the split (e.g., the part after a delimiter), you can index the list

df3['state'] = df3['place_with_parent_names'].str.split("|").str[0]

df3 = df3.drop(columns=["place_with_parent_names"])

df3

,property_type,area_m2,price_usd,lat,lon,state
0,Apartment,374.1,198546.39,26.272386538797807,-99.69333858664358,Mexico
1,condo,350.1,192501.01,21.179816414272228,-103.90928381708474,Mexico
3,villa,292.1,338234.86,18.402178035272414,-88.6815511701174,Mexico
4,land,291.3,143420.13,19.704376168280493,-98.6765463059634,Mexico
5,HOUSE,365.4,129193.79,18.975900448784394,-97.90542890349666,Mexico
...,...,...,...,...,...,...
693,condo,388.8,634100.21,19.17785272566725,-97.99839861164253,Mexico
694,house,305.1,204682.44,25.35786413008344,-100.56425311370224,Mexico
695,Apartamento,402.7,174512.33,18.875043194383732,-96.6902796375128,Mexico
696,HOUSE,183.9,158687.22,19.605826607779502,-98.59748258584555,Mexico
699,House,-409.1,311956.49,24.841765981145397,-99.93170869556052,Mexico

Concatenate DataFrames
You have three clean DataFrames, and now it's time to combine them into a single DataFrame so that you can conduct your analysis.

Task 1.2.7: Use pd.concat to stack df1, df2, and df3 vertically into a new DataFrame named df. After dropping rows with missing values in each cleaned frame, the result should have 1,650 rows and 6 columns: "property_type", "state", "lat", "lon", "area_m2", and "price_usd".

In [ ]:
# Stack the cleaned DataFrames by rows instead of side by side.
# ignore_index=True resets the index so the final DataFrame is clean and sequential.
df = pd.concat([df1, df2, df3], ignore_index=True)

df

,property_type,state,lat,lon,area_m2,price_usd
0,apartment,CIUDAD DE MEXICO,19.163374,-98.950584,108.6,7215680.28
1,Townhouse,Sonora,29.133288,-110.791352,-282.8,18965969.11
2,Terreno,QUINTANA ROO,19.717641,-88.401013,81.1,11297383.16
3,Apartamento,nuevo leon,25.535722,-99.979541,310.0,468041.13
4,Land,Ciudad de Mexico,20.067603,-99.145325,204.8,121627.07
...,...,...,...,...,...,...
1645,condo,Mexico,19.17785272566725,-97.99839861164253,388.8,634100.21
1646,house,Mexico,25.35786413008344,-100.56425311370224,305.1,204682.44
1647,Apartamento,Mexico,18.875043194383732,-96.6902796375128,402.7,174512.33
1648,HOUSE,Mexico,19.605826607779502,-98.59748258584555,183.9,158687.22
1649,House,Mexico,24.841765981145397,-99.93170869556052,-409.1,311956.49

Save df
The data is clean and in a single DataFrame, and now you need to save it as a CSV file so that you can examine it in your exploratory data analysis.

Task 1.2.8: Save df as a CSV file using the to_csv method. The file path should be "./data/mexico-real-estate-clean.csv". Be sure to set the index argument to False.

In [21]:
df.to_csv("mexico_real_estate_cleaned.csv", index=False)